// Generated by scripts/generate_release_files.py. Do not edit.
export const releaseData = {
  "releaseVersion": "4.0.0",
  "releaseTag": "v4.0.0",
  "releaseStatus": "submission-candidate",
  "directoryStatus": "preparing",
  "directoryURL": null,
  "plugins": [
    {
      "id": "gloamere-eval",
      "displayName": "Gloamere Eval",
      "version": "1.0.0-beta.1",
      "maturity": "beta",
      "publicRole": "maintainer",
      "skills": [
        "gloamere-skill-eval"
      ]
    },
    {
      "id": "gloamere-workflows",
      "displayName": "Gloamere Workflows",
      "version": "1.0.0",
      "maturity": "submission-candidate",
      "publicRole": "directory",
      "skills": [
        "gloamere-knowledge-capture",
        "gloamere-product-decision",
        "gloamere-visual-review"
      ]
    }
  ],
  "installProfiles": {
    "workflows": [
      "gloamere-workflows"
    ],
    "maintainer": [
      "gloamere-eval"
    ],
    "complete": [
      "gloamere-workflows",
      "gloamere-eval"
    ]
  }
} as const;

export type ReleaseData = typeof releaseData;
